// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQUdwHKtaMFJYebgogWMauJelWC3arK_M',
    appId: '1:629521207385:web:1e05e7a262a35c8f82e148',
    messagingSenderId: '629521207385',
    projectId: 'yournotes-flutter-app',
    authDomain: 'yournotes-flutter-app.firebaseapp.com',
    storageBucket: 'yournotes-flutter-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvfcclbuWu82XlsPi5Xd8ih56iItUjyyY',
    appId: '1:629521207385:android:dc9ec92178722e2d82e148',
    messagingSenderId: '629521207385',
    projectId: 'yournotes-flutter-app',
    storageBucket: 'yournotes-flutter-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAypkMuBFZPdJFfy_VVUnbH7p73eQdmwxI',
    appId: '1:629521207385:ios:a626c535e853ad6b82e148',
    messagingSenderId: '629521207385',
    projectId: 'yournotes-flutter-app',
    storageBucket: 'yournotes-flutter-app.appspot.com',
    iosClientId: '629521207385-f2rp33of2g1daephjtoud8shj0s2vudh.apps.googleusercontent.com',
    iosBundleId: 'com.moemanii.yournotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAypkMuBFZPdJFfy_VVUnbH7p73eQdmwxI',
    appId: '1:629521207385:ios:a626c535e853ad6b82e148',
    messagingSenderId: '629521207385',
    projectId: 'yournotes-flutter-app',
    storageBucket: 'yournotes-flutter-app.appspot.com',
    iosClientId: '629521207385-f2rp33of2g1daephjtoud8shj0s2vudh.apps.googleusercontent.com',
    iosBundleId: 'com.moemanii.yournotes',
  );
}
